In [4]:
import numpy as np

r = np.vstack([range(10),range(10,20)])

In [33]:
print(r)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [32]:
r[-1,::2]

array([10, 12, 14, 16, 18])

In [57]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    t,*f,l = person.split(' ')
    return ''.join([t,l])

list(map(split_title_and_name, people))


['Dr.Brooks', 'Dr.Collins-Thompson', 'Dr.Vydiswaran', 'Dr.Romero']

In [61]:
t,*f,l = 'Dr. VG Vinod Vydiswaran'.split(' ')
print(''.join([t,l]))

Dr.Vydiswaran


In [77]:
def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

True
True
True
True


In [72]:

(lambda x:person.split()[0] + ' ' + x.split()[-1])

6

In [74]:
#option 2
list(map(split_title_and_name, people)) == list(map(lambda person:person.split()[0] + ' ' + person.split()[-1],people))

True

In [ ]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = []

In [81]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(old)

[[1 1 1]
 [1 1 1]]


In [79]:
print(old)

[[0 0 1]
 [1 1 1]]


In [82]:
['a', 'b', 'c'] + [1, 2, 3]


['a', 'b', 'c', 1, 2, 3]

In [83]:
type(lambda x: x+1) 

function

In [93]:
r = np.array(range(36)).reshape(6,6)

In [94]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [95]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [1]:
import pandas as pd

/Users/vishalmishra/anaconda/envs/py36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/vishalmishra/anaconda/envs/py36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [5]:
s = pd.Series(np.random.randint(0,1000,10000))


In [6]:
%%timeit -n 100
summary = 0 
for iteam in s:
    summary += iteam

643 µs ± 22.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%%timeit -n 100
summary = np.sum(s)

115 µs ± 20.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [53]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])

In [54]:
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [22]:
df['Item Purchased']

Store 1        Dog Food
Store 1    Kitty Litter
Store 2       Bird Seed
Name: Item Purchased, dtype: object

In [23]:
df['Cost'] *= 0.80

In [24]:
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  18.0
Store 1  Kevyn   Kitty Litter   2.0
Store 2  Vinod      Bird Seed   4.0

In [42]:
df[(df['Cost']>3.0)]['Name']

Store 1    Chris
Store 2    Vinod
Name: Name, dtype: object

In [43]:
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [66]:
df["Location"] = df.index
df.reset_index()
df.set_index(['Location','Name'],inplace=True)

In [82]:
df

Item Purchased  Cost
Location Name                      
Store 1  Chris       Dog Food  22.5
         Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [86]:
df.loc[['Location','Name']] 

Empty DataFrame
Columns: [Item Purchased, Cost]
Index: []

In [87]:
df = df.append(pd.Series(data={'Cost': 3.00, 'Item Purchased': 'Kitty Food'}, name=('Store 2', 'Kevyn')))

In [88]:
df

Item Purchased  Cost
Location Name                      
Store 1  Chris       Dog Food  22.5
         Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0
         Kevyn     Kitty Food   3.0

In [94]:
df.index

MultiIndex(levels=[['Store 1', 'Store 2'], ['Chris', 'Kevyn', 'Vinod']],
           labels=[[0, 0, 1, 1], [0, 1, 2, 1]],
           names=['Location', 'Name'])